routes/web.php
<?php

/**
 * 后台路由组
 */
Route::group(['middleware'=>'admin.route','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','IndexController@index')->name('index');
    // 栏目资源路由
    Route::resource('category','CategoryController');
    // 文章资源路由（新闻）
    Route::resource('article','ArticleController');
    // 轮播图资源路由
    Route::resource('slide','SlideController');
    // 关于我们资源路由
    Route::resource('about','AboutController');

});

// 入口路由
Route::get('/',function (){
    return redirect('/home/index');
});

/**
 *  前后路由组
 */

Route::group(['prefix'=>'home','namespace'=>'Home','as'=>'home.'],function (){

    // 网站首页
    Route::get('index','IndexController@index')->name('index');

    // 关于我们
    Route::get('about','IndexController@about')->name('about');

    // 新闻列表
    Route::get('news','IndexController@news')->name('news');

    // 新闻详情页
    Route::get('news/{article}','IndexController@news_detail')->name('news_detail');

    // 案例展示
    Route::get('case_list','IndexController@case_list')->name('case_list');

    // 案例详情
    Route::get('case_detail/{article}','IndexController@case_detail')->name('case_detail');

    //加盟我们
    Route::get('service','IndexController@service')->name('service');

    //游戏专题
    Route::get('games','IndexController@games')->name('games');

    //联系我们
    Route::get('links','IndexController@links')->name('links');
});

/**
 *  公共路由组
 */
Route::group( ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],function (){
    Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
    Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
});

/**
 * 用户登录路由
 */
Route::group(['prefix'=>'user','namespace'=> 'User','as'=>'user.'],function (){
    Route::any('login','LoginController@login')->name('login');
    Route::post('store','LoginController@store')->name('store');
    Route::get('logout','LoginController@logout')->name('logout');
});

resources/views/admin/about_create.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.about.index')}}" class="nav-link">
                            关于列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.about.create')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            添加关于
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.about.store')}}" method="post">
            @csrf
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._about')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/about_edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.about.index')}}" class="nav-link">
                            关于列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.about.edit',$about)}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            编辑关于
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.about.update',$about)}}" method="post">
            @csrf
            @method('PUT')
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._about')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/about_index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.about.index')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            关于列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.about.create')}}" class="nav-link">
                            添加关于
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="card-body">
            <table class="table text-center">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>文章标题</th>
                    <th>所属栏目</th>
                    <th>发表时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($abouts as $about)
                    <tr>
                        <td scope="row">{{$about['id']}}</td>
                        <td style="max-width: 80px;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;"
                            title="{{$about['title']}}">{{$about['title']}}</td>
                        <td>
                            {{$about->category['title']}}
                        </td>
                        <td>
                            {{$about->created_at->diffForHumans()}}
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                <a href="{{route('admin.about.edit',$about)}}" class="btn btn-light">编辑关于</a>
                                <button type="button" class="btn btn-white" onclick="del(this)">删除关于</button>
                                <form action="{{route('admin.about.destroy',$about)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {{$abouts->links()}}
                </ul>
            </nav>
        </div>
    </div>
@endsection

@push('js')
    <script>
        function del(obj) {
            if(confirm('确认删除吗?')){
                $(obj).next().submit();
            }
        }
    </script>
@endpush

resources/views/admin/article_create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.article.index')}}" class="nav-link">
                            新闻列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.article.create')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            添加新闻
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.article.store')}}" method="post">
            @csrf
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._article')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/article_edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.article.index')}}" class="nav-link">
                            新闻列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.article.edit',$article)}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            编辑新闻
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.article.update',$article)}}" method="post">
            @csrf
            @method('PUT')
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._article')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/article_index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.article.index')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            新闻列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.article.create')}}" class="nav-link">
                            添加新闻
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="card-body">
            <table class="table text-center">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>文章标题</th>
                    <th>所属栏目</th>
                    <th>发表时间</th>
                    <th>作者</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($articles as $article)
                    <tr>
                        <td scope="row">{{$article['id']}}</td>
                        <td style="max-width: 80px;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;"
                            title="{{$article['title']}}">{{$article['title']}}</td>
                        <td>
                            {{$article->category['title']}}
                        </td>
                        <td>
                            {{$article->created_at->diffForHumans()}}
                        </td>
                        <td>
                            {{$article->author}}
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                <a href="{{route('admin.article.edit',$article)}}" class="btn btn-light">编辑新闻</a>
                                <a href="" class="btn btn-light">预览新闻</a>
                                <button type="button" class="btn btn-white" onclick="del(this)">删除新闻</button>
                                <form action="{{route('admin.article.destroy',$article)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {{$articles->links()}}
                </ul>
            </nav>
        </div>
    </div>
@endsection

@push('js')
    <script>
        function del(obj) {
            if(confirm('确认删除吗?')){
                $(obj).next().submit();
            }
        }
    </script>
@endpush

resources/views/admin/category_create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.category.index')}}" class="nav-link">
                            栏目列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.category.create')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            添加栏目
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.category.store')}}" method="post">
            @csrf
            {{--表单部分--}}
            <div class="card-body">
                <div class="card">
                    <div class="card-header">
                        基本设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>栏目名称</label>
                            <input type="text" name="title" class="form-control" placeholder="请输入栏目名称"
                                   aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label>父级栏目</label>
                            <select name="parent_id" class="form-control">
                                <option value="0">顶级栏目</option>
                                @foreach($categories as $category)
                                    <option value="{{$category['id']}}">
                                        {!! $category['_title'] !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>栏目描述</label>
                            <textarea name="description" class="form-control" rows="3" placeholder="请输入栏目描述"></textarea>
                        </div>
                        <div class="form-group">
                            <label>封面栏目</label>
                            <div class="custom-control custom-checkbox-toggle">
                                <input type="checkbox" class="custom-control-input" name="is_home" value="0"
                                       id="is_home">
                                <label class="custom-control-label" for="is_home"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        模板设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>封面模板</label>
                            <input type="text" name="home_template" class="form-control"
                                   value="{{old('home_template','home')}}">
                        </div>
                        <div class="form-group">
                            <label>列表页模板</label>
                            <input type="text" name="list_template" class="form-control"
                                   value="{{old('home_template','list')}}">
                        </div>
                        <div class="form-group">
                            <label>文章内容页模板</label>
                            <input type="text" name="content_template" class="form-control"
                                   value="{{old('home_template','content')}}">
                        </div>
                    </div>
                </div>
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category_edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.category.index')}}" class="nav-link">
                            栏目列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.category.edit',$category)}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            编辑栏目
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.category.update',$category)}}" method="post">
            @csrf
            @method('PUT')
            {{--表单部分--}}
            <div class="card-body">
                <div class="card">
                    <div class="card-header">
                        基本设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>栏目名称</label>
                            <input type="text" name="title" class="form-control" placeholder="请输入栏目名称"
                                   value="{{$category['title']}}" aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label>父级栏目</label>
                            <select name="parent_id" class="form-control">
                                <option value="0">顶级栏目</option>
                                @foreach($categories as $cat)
                                    <option value="{{$cat['id']}}"
                                            {{$cat['is_parent']?'selected':''}}
                                            {{$cat['id'] == $category['id'] || $cat['is_child'] ? 'disabled' : ''}}>
                                        {!! $cat['_title'] !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>栏目描述</label>
                            <textarea name="description" class="form-control" rows="3" placeholder="请输入栏目描述"></textarea>
                        </div>
                        <div class="form-group">
                            <label>封面栏目</label>
                            <div class="custom-control custom-checkbox-toggle">
                                <input type="checkbox" class="custom-control-input" name="is_home" value="1"
                                       id="is_home" {{$category['is_home']?'checked':''}}>
                                <label class="custom-control-label" for="is_home"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        模板设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>封面模板</label>
                            <input type="text" name="home_template" class="form-control"
                                   value="{{old('home_template','home')}}">
                        </div>
                        <div class="form-group">
                            <label>列表页模板</label>
                            <input type="text" name="list_template" class="form-control"
                                   value="{{old('home_template','list')}}">
                        </div>
                        <div class="form-group">
                            <label>文章内容页模板</label>
                            <input type="text" name="content_template" class="form-control"
                                   value="{{old('home_template','content')}}">
                        </div>
                    </div>
                </div>
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category_index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.category.index')}}" class="nav-link active" style="padding-bottom:9px;">
                            栏目列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.category.create')}}" class="nav-link">
                            添加栏目
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="card-body">
            <div class="card">
                <table class="table table-{1:striped|sm|bordered|hover|inverse} table-inverse text-center">
                    <thead class="thead-inverse|thead-default">
                    <tr>
                        <th>编号</th>
                        <th>分类名称</th>
                        <th>父级分类名</th>
                        <th>封面栏目</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td scope="row">{{$category['id']}}</td>
                            <td>{{$category['title']}}</td>
                            <td>
                                @if($category['parent_id'] == 0)
                                    顶级栏目
                                @else
                                    {{$category['parent_category']['title']}}
                                @endif
                            </td>
                            <td>
                                @if($category['is_home']==1)
                                    <span class="fe fe-check-circle text-info"></span>
                                @else
                                    <span class="fe fe-x-circle text-secondary"></span>
                                @endif
                            </td>
                            <td>{{$category->created_at->diffForHumans()}}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                    <a href="{{route('admin.category.edit',$category)}}" class="btn btn-light">编辑分类</a>
                                    <button class="btn btn-white" onclick="del(this)">删除分类</button>
                                    <form type="button" action="{{route('admin.category.destroy',$category)}}"
                                          method="post">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer text-muted">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {{$categories->links()}}
                </ul>
            </nav>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function del(m) {
            if(confirm('确认删除吗？')){
                $(m).next().submit();
            }
        }
    </script>
@endpush

resources/views/admin/slide_create.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.slide.index')}}" class="nav-link">
                            幻灯片列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.slide.create')}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            添加幻灯片
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.slide.store')}}" method="post">
            @csrf
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._slide')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/slide_edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.slide.index')}}" class="nav-link">
                            幻灯片列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.slide.edit',$slide)}}" class="nav-link active"
                           style="padding-bottom: 9px;">
                            编辑幻灯片
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.slide.update',$slide)}}" method="post">
            @csrf
            @method('PUT')
            {{--表单部分--}}
            <div class="card-body">
                @include('admin.layouts._slide')
            </div>
            {{--提交按钮--}}
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/slide_index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="card mt-2">
        {{--头部tab按钮--}}
        <div class="card-header">
            <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                    <li class="nav-item">
                        <a href="{{route('admin.slide.index')}}" class="nav-link active" style="padding-bottom: 9px;">
                            幻灯片列表
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.slide.create')}}" class="nav-link "
                        >
                            添加幻灯片
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <form action="{{route('admin.slide.store')}}" method="post">
            @csrf
            {{--表单部分--}}
            <div class="card-body">
                <table class="table text-center align">
                    <thead>
                    <tr>
                        <th>编号</th>
                        <th>幻灯片描述</th>
                        <th>跳转链接</th>
                        <th>图片</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($slides as $slide)
                        <tr>
                            <td scope="row">{{$slide['id']}}</td>
                            <td>{{$slide['title']}}</td>
                            <td>
                                <a href="{{$slide['url']}}" target="_blank">{{$slide['url']}}</a>
                            </td>
                            <td>
                                <div class="avatar avatar-lg avatar-4by3">
                                    <a href="{{$slide['image']}}" target="_blank">
                                        <img src="{{$slide['image']}}" alt="..." class="avatar-img rounded"
                                        style="width:50px; height:50px;">
                                    </a>
                                </div>
                            </td>
                            <td>{{$slide->created_at}}</td>
                            <td class="text-right">
                                <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                    <a href="{{route('admin.slide.edit',$slide)}}" class="btn btn-light">编辑幻灯片</a>
                                    <button type="button" class="btn btn-white" onclick="del(this)">删除幻灯片</button>
                                    <form action="{{route('admin.slide.destroy',$slide)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </form>
    </div>
@endsection

@push('js')
    <script>
        function del(obj) {
            if(confirm('确认删除吗?')){
                $(obj).next().submit();
            }
        }
    </script>
@endpush