routes/web.php
<?php

/**
 * 后台路由组
 */
Route::group(['middleware'=>'admin.route','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','IndexController@index')->name('index');
    // 栏目资源路由
    Route::resource('category','CategoryController');
    // 文章资源路由（新闻）
    Route::resource('article','ArticleController');
    // 轮播图资源路由
    Route::resource('slide','SlideController');
    // 关于我们资源路由
    Route::resource('about','AboutController');

});

// 入口路由
Route::get('/',function (){
    return redirect('/home/index');
});

/**
 *  前后路由组
 */

Route::group(['prefix'=>'home','namespace'=>'Home','as'=>'home.'],function (){

    // 网站首页
    Route::get('index','IndexController@index')->name('index');

    // 关于我们
    Route::get('about','IndexController@about')->name('about');

    // 新闻列表
    Route::get('news','IndexController@news')->name('news');

    // 新闻详情页
    Route::get('news/{article}','IndexController@news_detail')->name('news_detail');

    // 案例展示
    Route::get('case_list','IndexController@case_list')->name('case_list');

    // 案例详情
    Route::get('case_detail/{article}','IndexController@case_detail')->name('case_detail');

    //加盟我们
    Route::get('service','IndexController@service')->name('service');

    //游戏专题
    Route::get('games','IndexController@games')->name('games');

    //联系我们
    Route::get('links','IndexController@links')->name('links');
});

/**
 *  公共路由组
 */
Route::group( ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],function (){
    Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
    Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
});

/**
 * 用户登录路由
 */
Route::group(['prefix'=>'user','namespace'=> 'User','as'=>'user.'],function (){
    Route::any('login','LoginController@login')->name('login');
    Route::post('store','LoginController@store')->name('store');
    Route::get('logout','LoginController@logout')->name('logout');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/User/LoginController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LoginController extends Controller
{
    // 加载登录页面的方法
    public function login(){
        return view('user.login');
    }

    // 保存登录数据的方法
    public function store(Request $request){
        // attemp验证方法，会拿着表单提交过来的数据跟后台数据做比较，如果两者匹配，就通过。返回布尔值
       $status = \Auth::attempt([
           'email' =>$request->get('email'),
           'password' =>$request->get('password')
       ]);
       if($status){
           return redirect(route('admin.index'))->with('success','登录成功！');
       }else{
           return back()->with('error','用户名或密码错误');
       }
    }
    // 退出登录方法
    public function logout(){
        auth()->logout();
        return redirect(route('user.login'))->with('success','退出成功！');
    }
}

resources/views/user/login.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <!-- Libs CSS -->
    <link rel="stylesheet" href="{{asset('org/admin')}}/fonts/feather/feather.min.css">
    <link rel="stylesheet" href="{{asset('org/admin')}}/libs/highlight/styles/vs2015.min.css">
    <link rel="stylesheet" href="{{asset('org/admin')}}/libs/quill/dist/quill.core.css">
    <link rel="stylesheet" href="{{asset('org/admin')}}/libs/select2/dist/css/select2.min.css">
    <link rel="stylesheet" href="{{asset('org/admin')}}/libs/flatpickr/dist/flatpickr.min.css">

    <link href="{{asset('org/admin')}}/css/theme-dark.min.css" rel="" data-toggle="theme"
          data-theme-mode="dark">
    <link href="{{asset('org/admin')}}/css/theme.min.css" rel="" data-toggle="theme" data-theme-mode="light">

    <style>
        body {
            display: none;
        }
    </style>
    <script src="{{asset('org/admin/js/sweetalert.min.js')}}"></script>
    <script>
        var themeMode = (localStorage.getItem('dashkitThemeMode')) ? localStorage.getItem('dashkitThemeMode') : 'light';
        var themeFile = document.querySelector('[data-toggle="theme"][data-theme-mode="' + themeMode + '"]');

        // Enable stylesheet
        themeFile.rel = 'stylesheet';

        // Enable body content
        themeFile.addEventListener('load', function () {
            document.body.style.display = 'block';
        });
    </script>
    <title>后台登录系统</title>
    @include('layouts._hdjs')
</head>
<body class="d-flex align-items-center bg-auth border-top border-top-2 border-primary">
@include('layouts._message')
<div class="container-fluid">
    <div class="row align-items-center justify-content-center">
        <div class="col-12 col-md-5 col-lg-6 col-xl-4 px-lg-6 my-5">
            <!-- Heading -->
            <h1 class="display-4 text-center mb-3">双猴管理系统</h1>
            <!-- Subheading -->
            <p class="text-muted text-center mb-5">欢迎使用本系统！</p>
            <!-- Form -->
            <form method="post" action="{{route('user.store')}}">
            @csrf
            <!-- Email address -->
                <div class="form-group">
                    <label>邮箱</label>
                    <input type="email" name="email" class="form-control">
                </div>
                <!-- Password -->
                <div class="form-group">
                    <label>密码</label>
                    <div class="input-group input-group-merge">
                        <input type="password" name="password" class="form-control form-control-appended">
                        <div class="input-group-append">
                          <span class="input-group-text">
                            <i class="fe fe-eye"></i>
                          </span>
                        </div>
                    </div>
                </div>
                <button class="btn btn-lg btn-block btn-primary mb-3">登录</button>

                {{--<div class="text-center">--}}
                    {{--<small class="text-muted text-center">--}}
                        {{--还没有网站帐号? <a href="{{route('register')}}">注册</a>--}}
                        {{--<a href="{{route('findPassword')}}">找回密码</a>--}}
                    {{--</small>--}}
                {{--</div>--}}
            </form>
        </div>
        <div class="col-12 col-md-7 col-lg-6 col-xl-8 d-none d-lg-block">
            <!-- Image -->
            <div class="bg-cover vh-100 mt--1 mr--3"
                 style="background-image: url({{asset('org/admin')}}/img/covers/auth-side-cover.jpg);"></div>
        </div>
    </div>
</div>
</body>
</html>