routes/web.php
<?php

/**
 * 后台路由组
 */
Route::group(['middleware'=>'admin.route','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','IndexController@index')->name('index');
    // 栏目资源路由
    Route::resource('category','CategoryController');
    // 文章资源路由（新闻）
    Route::resource('article','ArticleController');
    // 轮播图资源路由
    Route::resource('slide','SlideController');
    // 关于我们资源路由
    Route::resource('about','AboutController');

});

// 入口路由
Route::get('/',function (){
    return redirect('/home/index');
});

/**
 *  前后路由组
 */

Route::group(['prefix'=>'home','namespace'=>'Home','as'=>'home.'],function (){

    // 网站首页
    Route::get('index','IndexController@index')->name('index');

    // 关于我们
    Route::get('about','IndexController@about')->name('about');

    // 新闻列表
    Route::get('news','IndexController@news')->name('news');

    // 新闻详情页
    Route::get('news/{article}','IndexController@news_detail')->name('news_detail');

    // 案例展示
    Route::get('case_list','IndexController@case_list')->name('case_list');

    // 案例详情
    Route::get('case_detail/{article}','IndexController@case_detail')->name('case_detail');

    //加盟我们
    Route::get('service','IndexController@service')->name('service');

    //游戏专题
    Route::get('games','IndexController@games')->name('games');

    //联系我们
    Route::get('links','IndexController@links')->name('links');
});

/**
 *  公共路由组
 */
Route::group( ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],function (){
    Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
    Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
});

/**
 * 用户登录路由
 */
Route::group(['prefix'=>'user','namespace'=> 'User','as'=>'user.'],function (){
    Route::any('login','LoginController@login')->name('login');
    Route::post('store','LoginController@store')->name('store');
    Route::get('logout','LoginController@logout')->name('logout');
});

resources/views/layouts/_hdjs.blade.php
<script>
    window.hdjs={};
        //组件目录必须绝对路径
        window.hdjs.base = '/org/hdjs';
        //上传文件后台地址 ，这里一般是填写路由地址或者写好的接口地址的
        window.hdjs.uploader = '{{route('common.uploader.make')}}?';
        //获取图片文件列表的后台地址 ，就是展示已经上传过的图片列表
        window.hdjs.filesLists = '{{route('common.uploader.lists')}}?';
</script>
<script src="/org/hdjs/require.js"></script>
<script src="/org/hdjs/config.js"></script>

{{--当页面把页面上的样式都注销掉的时候，bootstrap也会被注销，所以在这里要手动引入一下--}}
<script>
    require(['bootstrap']);
</script>

resources/views/layouts/_message.blade.php
@if($errors->count()>0)
    <script>
        swal({
            text: "@foreach($errors->all() as $error) {{$error}}\n  @endforeach",
            button: false,
            icon: 'info'
        });
    </script>
@endif

@if(session()->has('success'))
    <script>
        swal({
            text: "{{session()->get('success')}}",
            button: false,
            icon: 'success'
        });
    </script>
@endif

@if(session()->has('error'))
    <script>
        swal({
            text: "{{session()->get('error')}}",
            button: false,
            icon: 'error'
        });
    </script>
@endif